name: Build/Release

on: push

jobs:
  release:
    name: Build Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.x' # or the specific version you need

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Setup environment
        run: node ./scripts/prepare_ci
        env:
          HIVESQL_USERNAME: ${{ secrets.HIVESQL_USERNAME }}
          HIVESQL_PASSWORD: ${{ secrets.HIVESQL_PASSWORD }}

      - name: Build/Release Electron app
        env:
          NODE_OPTIONS: --max_old_space_size=8096

        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
